apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminapp-dep
  namespace: demospace
  labels:
    partof: adminapp-label
spec:
  selector:
    matchLabels:
      app: adminapp-pod-label
  replicas: 1
  template:
    metadata:
      name: adminapp-pod
      namespace: demospace
      labels:
        app: adminapp-pod-label
        partof: adminapp-label
    spec:
      containers:
      - name: adminapp
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_db
          - name: POSTGRES_HOST
            value: postgres-svc
        image: aayush21/admin:charlie
---
apiVersion: v1     
kind: Service
metadata:
  name: adminapp-svc
  namespace: demospace
  labels:
    partof: adminapp-label
spec:
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 32679
  selector:
    app: adminapp-pod-label
  type: NodePort
