apiVersion: apps/v1
kind: Deployment
metadata:
  name: authapp-dep
  namespace: demospace
  labels:
    partof: authapp-label
spec:
  selector:
    matchLabels:
      app: authapp-pod-label
  replicas: 1
  template:
    metadata:
      name: authapp-pod
      namespace: demospace
      labels:
        app: authapp-pod-label
        partof: authapp-label
    spec:
      containers:
      - name: authapp
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_db
          - name: POSTGRES_HOST
            value: postgres-svc
        image: prasoon0459/auth_app:2.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: authapp-svc
  namespace: demospace
  labels:
    partof: authapp-label
spec:
  ports:
    - protocol: TCP
      port: 8079
      targetPort: 8079
      nodePort: 32678
  selector:
    app: authapp-pod-label
  type: NodePort
