apiVersion: v1
kind: Namespace
metadata:
   name: demospace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: demospace
  labels:
    partof: postgres-label
data:
  postgres_user: postgres
  postgres_password: password
  postgres_db: testdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dep
  namespace: demospace
  labels:
    partof: postgres-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-pod
  template:
    metadata:
      name: postgres-pod
      labels:
        app: postgres-pod
        partof: postgres-label
        namespace: demospace
    spec:
      volumes:
        - name: postgres-storage
          hostPath:
            path: /var/lib/postgres-k8s/data
            type: DirectoryOrCreate
      containers:
        - image: postgres
          name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: demospace
  labels:
    partod: postgres-label
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres-pod