# mkdir target/dependency
# (cd target/dependency; jar -xf ../*.jar)
# docker build -t aayush21/admin:<tag> .

FROM openjdk:11-jre-slim
VOLUME /tmp
ARG DEPENDENCY=target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT ["java","-cp","app:app/lib/*","com.dev.admin.admin.DemoApplication"]